GET http://localhost:3000/subscribers

### 
GET http://localhost:3000/subscribers/5eafe82a6c3f3a7e84aef81e

### 
POST http://localhost:3000/subscribers
Content-Type: application/json

{
	"name": "Rohan Naik",
	"subscribedToChannel" : "Web Dev School"
}

###
DELETE  http://localhost:3000/subscribers/5eafe728c068da49442f528a


###
PATCH   http://localhost:3000/subscribers/5eafe82a6c3f3a7e84aef81e
Content-Type: application/json

{
	"name": "Archana Naik",
	"subscribedToChannel" : "Pharma Channel"
}

